services:
  judge:
    image: pigeon-oj/judge-dev
    privileged: true
    pid: host
    cgroup: host
    env_file: judge.env
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /run/systemd/private
        target: /run/systemd/private
      - type: bind
        source: ./config.json
        target: /app/config.json
      - type: bind
        source: /tmp/hustoj-dev
        target: /volume
    build:
      dockerfile: ./tools/test-compose/judge.Dockerfile
      context: ../..

  hustoj:
    image: pigeon-oj/hustoj-dev
    volumes:
      - type: bind
        source: /tmp/hustoj-dev
        target: /volume
    build:
      dockerfile: ./hustoj.Dockerfile
    ports:
      - "3000:80"

  mysql:
    image: pigeonojdev/compose-db:0.0.0-alpha.0
    env_file: db.env
    ports:
      - "3306:3306"
    restart: always
