FROM debian:bookworm-slim

RUN apt-get update && apt-get install --no-install-recommends libc6-dev -y
RUN apt-get install --no-install-recommends clang-19 -y
RUN apt-get install --no-install-recommends gnustep gnustep-devel libgnustep-base-dev libobjc-12-dev -y
RUN apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN mkdir /app
ADD build.sh /app/build.sh
ADD run.sh /app/run.sh
RUN chmod +x /app/*.sh
