name: release-runtime

on:
  workflow_dispatch:
    inputs:
      version:
        description: code tag
        required: true

env:
  cr_coding: g-yuie8424-docker.pkg.coding.net
  cr_acr: registry.cn-hangzhou.aliyuncs.com
  cr_tcr: ccr.ccs.tencentyun.com

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Coding Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.cr_coding }}
          username: ${{ secrets.CODING_USERNAME }}
          password: ${{ secrets.CODING_TOKEN }}
      - name: Login to acr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.cr_acr }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.CR_TOKEN }}
      - name: Login to tcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.cr_tcr }}
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.CR_TOKEN }}
      - name: Build and push - c
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/c/dockerfile
          context: ./runtime/c
          push: true
          tags: |
            pigeonojdev/runtime-c:${{ github.event.inputs.version }}
      - name: Build and push - cpp
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/cpp/dockerfile
          context: ./runtime/cpp
          push: true
          tags: |
            pigeonojdev/runtime-cpp:${{ github.event.inputs.version }}
      - name: Build and push - pascal
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/pascal/dockerfile
          context: ./runtime/pascal
          push: true
          tags: |
            pigeonojdev/runtime-pascal:${{ github.event.inputs.version }}
      - name: Build and push - java
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/java/dockerfile
          context: ./runtime/java
          push: true
          tags: |
            pigeonojdev/runtime-java:${{ github.event.inputs.version }}
      - name: Build and push - ruby
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/ruby/dockerfile
          context: ./runtime/ruby
          push: true
          tags: |
            pigeonojdev/runtime-ruby:${{ github.event.inputs.version }}
      - name: Build and push - bash
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/bash/dockerfile
          context: ./runtime/bash
          push: true
          tags: |
            pigeonojdev/runtime-bash:${{ github.event.inputs.version }}
      - name: Build and push - python
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/python/dockerfile
          context: ./runtime/python
          push: true
          tags: |
            pigeonojdev/runtime-python:${{ github.event.inputs.version }}
      - name: Build and push - php
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/php/dockerfile
          context: ./runtime/php
          push: true
          tags: |
            pigeonojdev/runtime-php:${{ github.event.inputs.version }}
      - name: Build and push - perl
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/perl/dockerfile
          context: ./runtime/perl
          push: true
          tags: |
            pigeonojdev/runtime-perl:${{ github.event.inputs.version }}
      - name: Build and push - csharp
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/csharp/dockerfile
          context: ./runtime/csharp
          push: true
          tags: |
            pigeonojdev/runtime-csharp:${{ github.event.inputs.version }}
      - name: Build and push - objectivec
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/objectivec/dockerfile
          context: ./runtime/objectivec
          push: true
          tags: |
            pigeonojdev/runtime-objectivec:${{ github.event.inputs.version }}
      - name: Build and push - freebasic
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/freebasic/dockerfile
          context: ./runtime/freebasic
          push: true
          tags: |
            pigeonojdev/runtime-freebasic:${{ github.event.inputs.version }}
      - name: Build and push - scheme
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/scheme/dockerfile
          context: ./runtime/scheme
          push: true
          tags: |
            pigeonojdev/runtime-scheme:${{ github.event.inputs.version }}
      - name: Build and push - lua
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/lua/dockerfile
          context: ./runtime/lua
          push: true
          tags: |
            pigeonojdev/runtime-lua:${{ github.event.inputs.version }}
      - name: Build and push - javascript
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/javascript/dockerfile
          context: ./runtime/javascript
          push: true
          tags: |
            pigeonojdev/runtime-javascript:${{ github.event.inputs.version }}
      - name: Build and push - golang
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/golang/dockerfile
          context: ./runtime/golang
          push: true
          tags: |
            pigeonojdev/runtime-golang:${{ github.event.inputs.version }}
      - name: Build and push - fortran
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/fortran/dockerfile
          context: ./runtime/fortran
          push: true
          tags: |
            pigeonojdev/runtime-fortran:${{ github.event.inputs.version }}
      - name: Build and push - matlab
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/matlab/dockerfile
          context: ./runtime/matlab
          push: true
          tags: |
            pigeonojdev/runtime-matlab:${{ github.event.inputs.version }}
      - name: Build and push - cobol
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/cobol/dockerfile
          context: ./runtime/cobol
          push: true
          tags: |
            pigeonojdev/runtime-cobol:${{ github.event.inputs.version }}
      - name: Build and push - r
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/r/dockerfile
          context: ./runtime/r
          push: true
          tags: |
            pigeonojdev/runtime-r:${{ github.event.inputs.version }}
      - name: Build and push - scratch3
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/scratch3/dockerfile
          context: ./runtime/scratch3
          push: true
          tags: |
            pigeonojdev/runtime-scratch3:${{ github.event.inputs.version }}
      - name: Build and push - cangjie
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/cangjie/dockerfile
          context: ./runtime/cangjie
          push: true
          tags: |
            pigeonojdev/runtime-cangjie:${{ github.event.inputs.version }}
      - name: Build and push - clang
        uses: docker/build-push-action@v6
        with:
          file: ./runtime/clang/dockerfile
          context: ./runtime/clang
          push: true
          tags: |
            pigeonojdev/runtime-clang:${{ github.event.inputs.version }}
